apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.Project.Name }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.Replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      web-app: {{ .Values.Project.Name }}
  template:
    metadata:
      labels:
        web-app: {{ .Values.Project.Name }}
    spec:
      containers:
      - env:
        - name: MARIADB_HOST
          value: {{ .Values.Container.Environment.MARIADB_HOST | quote }}
        - name: MARIADB_PORT_NUMBER
          value: {{ .Values.Container.Environment.MARIADB_PORT_NUMBER | quote }}
        - name: WORDPRESS_DATABASE_NAME
          value: {{ .Values.Project.Name }}
        - name: WORDPRESS_DATABASE_PASSWORD
          value: {{ .Values.Container.Environment.WORDPRESS_DATABASE_PASSWORD }}
        - name: WORDPRESS_DATABASE_USER
          value: {{ .Values.Container.Environment.WORDPRESS_DATABASE_USER }}
        image: bitnami/wordpress-nginx:latest
        imagePullPolicy: Always
        name: {{ .Values.Project.Name }}
        ports:
        - containerPort: {{ .Values.Port }}
          name: {{ .Values.Port }}tcp02
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: {{ .Release.Name }}
            path: /
            port: {{ .Values.Port }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 250m
            memory: 500Mi
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/conf/server_blocks/{{ .Values.Project.Name }}-server-block.conf
          name: config-nginx
          subPath: {{ .Values.Project.Name }}-server-block.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          items:
          - key: nginx
            path: {{ .Values.Project.Name }}-server-block.conf
          name: {{ .Release.Name }}-config
        name: config-nginx
